Piiii.web/Controllers/QuestionAnswersController.cs
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using System.Net;
using PagedList;
using System.Diagnostics;
using Piiii.web.Models;
using Piiii.domain;
using Piiii.service;

namespace Piiii.web.Controllers
{
    public class QuestionAnswersController : Controller
    {
        public AnswerService ans;
        public QuestionService qts;
        public QuizService qz;
        public float score_quest = 0;
        public float score = 0;


        public QuestionAnswersController()
        {
            qz = new QuizService();
            qts = new QuestionService();
            ans = new AnswerService();

        }

        // GET: QuestionAnswers
        public ActionResult Index(int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(qz.GetAll().ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult Index(string filtre)
        {
            var list = qz.GetMany();

            if (!String.IsNullOrEmpty(filtre))
            { list = list.Where(m => m.QuizName.ToString().Contains(filtre)).ToList(); }
            return View(list);
        }
        // GET: QuestionAnswers/Details/5
        public ActionResult Details(int id)
        {

            quiz q = qz.GetById(id);
            if (q == null)
            {
                return HttpNotFound();
            }

            return View(q);

            //return View(qz.GetById(id));
        }


        // GET: QuestionAnswers/Create
        public ActionResult loadQuiz(int id)
        {
            QuizQuestionAnswers qqa  = new QuizQuestionAnswers();
            qqa.quizId = id;
            quiz quiz = qz.GetById(id);

            var questions = qts.GetMany().Where(x => x.quiz_id_Quiz.Equals(quiz.id_Quiz));
            
            qqa.Questions = new List<questionModel>();
            qqa.answers = new List<answerModel>();
            foreach (question quest in questions)
                {
                    questionModel questionModel = new questionModel();
                    questionModel.id_Question = quest.id_Question;
                    questionModel.question_name = quest.question_name;
                    questionModel.question_description = quest.question_description;
                  questionModel.userchoice = null;

                var answers = ans.GetMany().Where(x => x.question_id_Question.Equals(quest.id_Question));


                    foreach (answer answ in answers)
                    {
                        answerModel answerModel = new answerModel();
                        answerModel.id_Answer = answ.id_Answer;
                        answerModel.question_id_Question = answ.question_id_Question;
                        answerModel.answer_name = answ.answer_name;
                        answerModel.flag = answ.flag;

                    qqa.answers.Add(answerModel);
                    

                }
               
                qqa.Questions.Add(questionModel);
                
            }

           
            return View(qqa);
        }

        // POST: QuestionAnswers/Create
        [HttpPost]
        public ActionResult loadQuiz(QuizQuestionAnswers qqa)
        {
            try
            {
               
                //TempData["score"] = 0;
                //TempData["score_quest"] = 0;
                if (qqa != null)
                {
                    quiz quiz = qz.GetById((int)qqa.quizId);
                    var id = quiz.id_Quiz;
                    var questions = qqa.Questions;
                    var answers = qqa.answers;
                    List<float> scores = new List<float>();
                    List<float> score_quests = new List<float>();
                    //  quiz.Result = 0;


                    foreach (var quest in questions)
                    {
                        
                        var qId = quest.id_Question;
                        question q = new question();
                        q = qts.GetById(qId);
                        q.userchoice = quest.userchoice;
                        qts.Commit();
                        //quest.userchoice= questions.Find(x=>x.id_Question==qId).userchoice;

                      // foreach (var answ in answers)
                        //{
                            //answer s = new answer();
                            //s = ans.GetById(answ.id_Answer);
                           // s.id_Answer = answ.id_Answer;
                          //  s.flag = answ.flag;
                          //  s.question_id_Question = answ.question_id_Question;
                            
                            if (q.userchoice.Equals(true))
                            {

                                score += 100 / questions.Count();
                            }
                        score = score+0;                                                                    
                       // }
                       // score_quests.Add(scores.Sum());
                        //TempData["score_quest"] = Convert.ToInt32(TempData["score"]) + Convert.ToInt32(TempData["score_quest"]);

                    }

                    qqa.score =(int) score;
                       
                  
                    // quiz.Result+= Convert.ToInt32(TempData["score_quest"]);
                    quiz.Result = qqa.score;
                    qz.Commit();
                    
                    SendEmail(quiz.Result);
                    // qz.Update(quiz);



                    return RedirectToAction("Details", new { id = qqa.quizId, otherParam = score_quests.Sum() });
                    //   return RedirectToAction("Index");
                    // return View(quiz);
                }
                else
                {
                    return new HttpNotFoundResult();

                }
            }
            
            catch
            {
                return View();
            }
        }



        [HttpPost]
        public ActionResult SendEmail(int? result)
        {
            try
            {
                var fromAddress = new MailAddress("iness.zaier@gmail.com", "Advyteam certifications");
                var toAddress = new MailAddress("ines.zaier@esprit.tn");
                const string fromPassword = "5otbtyflsif!<3";
                string subject = "Certification "; //your subject line
                string body = "Your certification score is : "+ result.ToString() ;// your body
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com", //example
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    Credentials = new NetworkCredential(fromAddress.Address, fromPassword),
                    Timeout = 20000
                };
                using (var message = new MailMessage(fromAddress, toAddress)
                {
                    Subject = subject,
                    Body = body

                })
                {
                    try
                    {
                        smtp.EnableSsl = true;
                        smtp.Send(message);
                        Debug.WriteLine("mail Send");
                    }
                    catch (Exception ex)
                    {
                        Debug.WriteLine("*****************************" + ex.ToString());
                    }

                }
            
                    return View();
                
            }
            catch (Exception)
            {
                ViewBag.Error = "Some Error";
            }
            return View();
        }



        // GET: QuestionAnswers/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: QuestionAnswers/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionAnswers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: QuestionAnswers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Piiii.web/Views/QuestionAnswers/Details.cshtml
@model Piiii.domain.quiz

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout1.cshtml";
}
<div class="colorlib-work">
    <div class="container">
        <h2>Details</h2>

        <div>
            <h4> @Html.DisplayFor(model => model.QuizName)</h4>
            <hr />
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.QuizName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.QuizName)
                </dd>



                <dt>
                    @Html.DisplayNameFor(model => model.formation1.catalog.nom_cat)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.formation1.catalog.nom_cat)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.formation1.description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.formation1.description)
                </dd>


                <dt>
                    @Html.DisplayNameFor(model => model.formation1.prerequis)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.formation1.prerequis)
                </dd>


                <dt>
                    @Html.DisplayNameFor(model => model.Result)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Result)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>
</div>
</div>

Piiii.web/Views/QuestionAnswers/Index.cshtml
@model PagedList.IPagedList<Piiii.domain.quiz>
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout1.cshtml";
}




<div class="colorlib-work">
    <div class="container">
        <h2>Certification catalog</h2>
        @using (Html.BeginForm())
        {
            <div class="row animate-box">
                <div class="col-md-6 col-md-offset-3">
                    <div class="row">
                        <div class="col-md-12">
                            <iframe width="560"
                                    height="315"
                                    src="https://www.youtube.com/embed/wCntbwSwoiI"
                                    frameborder="0"
                                    allowfullscreen>

                            </iframe>

                            <form class="form-inline qbstp-header-subscribe">
                                <div class="col-three-forth">
                                    <div class="form-group">
                                        <div>
                                            @Html.TextBox("filtre", "Search by name", new { @class = "form-control" })

                                        </div>

                                    </div>
                                </div>
                                <div class="col-one-third">
                                    <div class="form-group">
                                        <button type="submit" id="submit" class="btn btn-primary">Search Now</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        }

            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-md-4 animate-box">
                        <div class="work-grid">
                            
                            <div class="desc">
                                <h2><a href="#"> @Html.DisplayFor(modelItem => item.QuizName)</a></h2>
                                <p>Catalog :@Html.DisplayFor(modelItem => item.formation1.catalog.nom_cat)</p>
                                <p>Descrition :  @Html.DisplayFor(modelItem => item.formation1.description)</p>
                                <p>prerequis : @Html.DisplayFor(modelItem => item.formation1.prerequis)</p>
                                @Html.ActionLink("Pass", "loadQuiz", new { id = item.id_Quiz }) |
                                @Html.ActionLink("Details", "Details", new { id = item.id_Quiz })
                            </div>
                        </div>
                    </div>
                    
                }
            </div>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
</div>

Piiii.web/Views/QuestionAnswers/loadQuiz.cshtml
@model Piiii.web.Models.QuizQuestionAnswers

@{
    ViewBag.Title = "loadQuiz";
    Layout = "~/Views/Shared/Layout1.cshtml";
}

<script>
    $(document).ready(function () {
        $("input:checked").removeAttr("checked");
    });
</script>


<div class="colorlib-work">
    <div class="container">
        <h2>load Quiz</h2>
        @using (Html.BeginForm("loadQuiz", "QuestionAnswers", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="row cell">
                <div class="example bg-grayLighter" data-text="Directions">
                    <ul class="simple-list">
                        <li class="align-left">When you have made your selection for all statements, click on the button 'Submit.'</li>
                        <li class="align-left">Mark 'True' or 'False' for each statement.</li>
                        <li class="align-left">You must score 80%  to pass.</li>
                        <li class="align-left">You have a single attempt.</li>
                    </ul>
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="colorlib-work">
                <div class="row animate-box">
                    <div class="featured-wrap">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="featured-entry">

                                <div class="form-horizontal">

                                    <div class="row cell">
                                        <div class="row cell">
                                            <div class="panel" data-role="panel">
                                                <div class="heading">
                                                    <span class="title">  </span>
                                                </div>
                                                <div class="content">


                                                    <dl class="dl-horizontal">
                                                        @Html.HiddenFor(x => x.quizId)

                                                        @for (var i = 0; i < Model.Questions.Count(); i++)

                                                        {


                                                            @Html.HiddenFor(x => x.Questions[i].id_Question)

                                                            <dt> @Html.DisplayFor(q => q.Questions[i].question_name) </dt>
                                                            <dd>@Html.DisplayFor(q => q.Questions[i].question_description)</dd>
                                                            <br />
                                                            for (var j = 0; j < Model.answers.Count(); j++)
                                                            {
                                                                if (Model.answers[j].question_id_Question == Model.Questions[i].id_Question)
                                                                {
                                                                    @Html.HiddenFor(x => x.answers[j].id_Answer)
                                                                    <dt>
                                                                        @Html.RadioButtonFor(model => model.Questions[i].userchoice, Model.answers[j].flag, new { id = Model.answers[j].question_id_Question })
                                                                    </dt>

                                                                    <dd>@Html.Label(Model.answers[j].answer_name)</dd>
                                                                    <br />
                                                                }


                                                            }





                                                        }
                                                    </dl>
                                                    
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Submit" class="btn btn-default" />
                                            <input type="reset" value="Reset" class="btn btn-default" />
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        }

    </div>
</div>