Piiii.web/Controllers/missionexpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Piiii.data;
using Piiii.domain;

namespace Piiii.web.Controllers
{
    public class missionexpensesController : Controller
    {
        private Context db = new Context();

        // GET: missionexpenses
        public ActionResult Index()
        {
            var missionexpenses = db.missionexpenses.Include(m => m.mission).Include(m => m.user);
            return View(missionexpenses.ToList());
        }

        // GET: missionexpenses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            missionexpenses missionexpenses = db.missionexpenses.Find(id);
            if (missionexpenses == null)
            {
                return HttpNotFound();
            }
            return View(missionexpenses);
        }

        // GET: missionexpenses/Create
        public ActionResult Create()
        {
            ViewBag.mission_refrence = new SelectList(db.mission, "refrence", "description");
            ViewBag.user_userId = new SelectList(db.user, "userId", "email");
            return View();
        }

        // POST: missionexpenses/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "refrence,isApproved,totalRecovered,mission_refrence,cost,date,description,image,kilomtrage,totalCost,type,user_userId")] missionexpenses missionexpenses, HttpPostedFileBase file,int? id)
        {
         

            if (file != null)
            {
                string fileName = Path.GetFileName(file.FileName);
                string path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                file.SaveAs(path);
            }
            missionexpenses.user_userId = 2;
            missionexpenses.mission_refrence = id;
            missionexpenses.image = file.FileName;
            missionexpenses.date = System.DateTime.Now;
          
           
                db.missionexpenses.Add(missionexpenses);
                db.SaveChanges();
                return RedirectToAction("Index");
          
           

            //ViewBag.mission_refrence = new SelectList(db.mission, "refrence", "description", missionexpenses.mission_refrence);
            //ViewBag.user_userId = new SelectList(db.user, "userId", "email", missionexpenses.user_userId);
            //return View(missionexpenses);
        }

        // GET: missionexpenses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            missionexpenses missionexpenses = db.missionexpenses.Find(id);
            if (missionexpenses == null)
            {
                return HttpNotFound();
            }
            ViewBag.mission_refrence = new SelectList(db.mission, "refrence", "description", missionexpenses.mission_refrence);
            ViewBag.user_userId = new SelectList(db.user, "userId", "email", missionexpenses.user_userId);
            return View(missionexpenses);
        }

        // POST: missionexpenses/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "refrence,isApproved,totalRecovered,mission_refrence,cost,date,description,image,kilomtrage,totalCost,type,user_userId")] missionexpenses missionexpenses,HttpPostedFileBase file)
        {
            if (file != null)
            {
                string fileName = Path.GetFileName(file.FileName);
                string path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                file.SaveAs(path);
            }
          
            missionexpenses.image = file.FileName;
            missionexpenses.date = System.DateTime.Now;

          //  if (ModelState.IsValid)
            //{
                db.Entry(missionexpenses).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Expances");
           // }
            //ViewBag.mission_refrence = new SelectList(db.mission, "refrence", "description", missionexpenses.mission_refrence);
            //ViewBag.user_userId = new SelectList(db.user, "userId", "email", missionexpenses.user_userId);
            //return View(missionexpenses);
        }

        // GET: missionexpenses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            missionexpenses missionexpenses = db.missionexpenses.Find(id);
            if (missionexpenses == null)
            {
                return HttpNotFound();
            }
            return View(missionexpenses);
        }

        // POST: missionexpenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            missionexpenses missionexpenses = db.missionexpenses.Find(id);
            db.missionexpenses.Remove(missionexpenses);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

Piiii.web/Views/missionexpenses/Create.cshtml
@model Piiii.domain.missionexpenses

@{
    /**/

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout1.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "missionexpenses", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>missionexpenses</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @{
        var selectList = new SelectList(
            new List<SelectListItem>
            {
new SelectListItem {Text = "Transport", Value = "Transport"},
new SelectListItem {Text = "Hotel", Value = "Hotel"},
new SelectListItem {Text = "Resto", Value = "Resto"},
new SelectListItem {Text = "Other", Value = "Other"},
            }, "Value", "Text");
    }

    <div class="form-group">
        @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" id="lbox">
            @Html.DropDownListFor(model => model.type, selectList, "Default label", new { htmlAttributes = new { @class = "form-control" } })

            @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group" id="box" runat="server" visible="false">

        @Html.LabelFor(model => model.kilomtrage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.kilomtrage, new { htmlAttributes = new { @class = "form-control" } })

        </div>
    </div>




    <div class="form-group">
        <input type="file" name="file" id="file" class="btn-success" onclick="btnSave_Click" />

    </div>

    <script language="javascript">
        function Checkfiles() {
            var fup = document.getElementById('file');
            var fileName = fup.value;
            var ext = fileName.substring(fileName.lastIndexOf('.') + 1);
            if (ext == "gif" || ext == "GIF" || ext == "PNG" || ext == "png" || ext == "jpg" || ext == "JPG" || ext == "bmp" || ext == "BMP") {
                return true;
            }
            else {
                alert("Upload Gif,Bmp or Jpg images only");
                fup.focus();
                return false;
            }
        }
    </script>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />

        </div>
    </div>
</div>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#type").change(function () {
                if ($(this).val() != "Transport") {
                    $("#box").hide();
                } else {
                    $("#box").show();
                }
            });
        });
    </script>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Piiii.web/Views/missionexpenses/Delete.cshtml
@model Piiii.domain.missionexpenses

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>missionexpenses</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mission.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mission.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isApproved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.totalRecovered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalRecovered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kilomtrage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kilomtrage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.totalCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
           
        </div>
    }
</div>

Piiii.web/Views/missionexpenses/Details.cshtml
@model Piiii.domain.missionexpenses

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout1.cshtml";
}

<h2>Details</h2>

<div>
    <h4>missionexpenses</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <div id="box" runat="server" visible="false">
            <dt>
                @Html.DisplayNameFor(model => model.kilomtrage)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.kilomtrage)
            </dd>

        </div>


        <dd>

            <img style="width:300px; height:300px" src="@Url.Content("~/Uploads/"+Model.image)" />
        </dd>
    </dl>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#type").change(function () {
                if ($(this).val() != "Transport") {
                    $("#box").hide();
                } else {
                    $("#box").show();
                }
            });
        });
    </script>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.refrence }) |
    @Html.ActionLink("Back to List", "Index")
</p>


<style>
    /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
    #map {
        height: 600px;
    }
</style>
<div class="row"></div>
<div id="map">
    <script>
        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: { lat: 36.800072, lng: 10.187060 },
                zoom: 12
            });

            $.get("/Home/GetAllLocation", function (data, status) {
                var marker = [];
                var contentString = [];
                var infowindow = [];
                for (var i = 0; i < data.length; i++) {
                    marker[i] = new google.maps.Marker({
                        position: { lat: data[i].Lat, lng: data[i].Long },
                        map: map
                    });
                    //code events
                    contentString[i] = '<div id="content">' +
                        '<div id="siteNotice"></div>' +
                        '<h1 id="firstHeading" class="firstHeading">' + data[i].StoreName + '</h1>' +
                        '<div id="bodyContent"><p><b>' + data[i].Address + '</b><br>' +
                        '</div></div>';

                    infowindow[i] = new google.maps.InfoWindow({
                        content: contentString[i]
                    });
                    var markerValue = marker[i];
                    google.maps.event.addListener(marker[i], 'mouseover', (function (markerValue, i) {
                        return function () {
                            infowindow[i].open(map, marker[i]);
                        }
                    })(marker[i], i));
                    google.maps.event.addListener(marker[i], 'mouseout', (function (markerValue, i) {
                        return function () {
                            infowindow[i].close();
                        }
                    })(marker[i], i));
                }
            })
        }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5ZGyW3DWlaXpcb1lCoF5o3Iamovy4K_o&language=fr&callback=initMap"
            type="text/javascript" async defer></script>
</div>

Piiii.web/Views/missionexpenses/Edit.cshtml
@model Piiii.domain.missionexpenses

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout1.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "missionexpenses", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>missionexpenses</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.refrence)

    @{
        var selectList = new SelectList(
            new List<SelectListItem>
            {
new SelectListItem {Text = "Transport", Value = "Transport"},
new SelectListItem {Text = "Hotel", Value = "Hotel"},
new SelectListItem {Text = "Resto", Value = "Resto"},
new SelectListItem {Text = "Other", Value = "Other"},
            }, "Value", "Text");
    }

    <div class="form-group">
        @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" id="lbox">
            @Html.DropDownListFor(model => model.type, selectList, "Default label", new { htmlAttributes = new { @class = "form-control" } })

            @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group" id="box" runat="server" visible="false">
        @Html.LabelFor(model => model.kilomtrage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.kilomtrage, new { htmlAttributes = new { @class = "form-control" } })
         
        </div>
    </div>

    <div class="form-group">
        <input type="file" name="file" id="file" class="btn-success" />
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#type").change(function () {
                if ($(this).val() != "Transport") {
                    $("#box").hide();
                } else {
                    $("#box").show();
                }
            });
        });
    </script>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Piiii.web/Views/missionexpenses/Index.cshtml
@model IEnumerable<Piiii.domain.missionexpenses>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout1.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)

        </th>
        <th>
            @Html.DisplayNameFor(model => model.kilomtrage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.totalCost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.image)
            <img style="width:200px; height:200px" src="@Url.Content("~/Uploads/"+item.image)"  />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kilomtrage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.totalCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.refrence }) |
            @Html.ActionLink("Details", "Details", new { id=item.refrence }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.refrence })
        </td>
    </tr>



}

</table>