Piiii.web/Controllers/VisualizeDataController.cs
using Piiii.domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Piiii.data;
using Piiii.web.Models;

namespace Piiii.web.Controllers
{
    public class VisualizeDataController : Controller
    {
        private Context db = new Context();

        public ActionResult ColumnChart()
        {
            return View();
        }

        public ActionResult PieChart()
        {
            return View();
        }

        public ActionResult LineChart()
        {
            return View();
        }

        public ActionResult VisualizeStudentResult()
        {
            return Json(Result(), JsonRequestBehavior.AllowGet);
        }

        public List<StatResult> Result()
        {     
            var timesheet = db.timesheet.ToList();
            List<StatResult> stdResult = new List<StatResult>();

            stdResult.Add(new StatResult() {
                stdName = "Ahmed",
                marksObtained = 88

            });
            stdResult.Add(new StatResult()
            {
                stdName = "Houssem",
                marksObtained = 50

            });
            stdResult.Add(new StatResult()
            {
                stdName = "Ali",
                marksObtained = 120

            }); stdResult.Add(new StatResult()
            {
                stdName = "Hassen",
                marksObtained = 80

            });
            return stdResult;
        }
    }
}

Piiii.web/Views/VisualizeData/ColumnChart.cshtml
@{
    Layout = "~/Views/Shared/Layout1.cshtml";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeStudentResult", "VisualizeData")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Jour');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.stdName, obj.marksObtained]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Employes Performance",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('columnchart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnchart_div"></div>
    <a href="@Url.Action("PieChart")" class="btn btn-danger">Pie Chart</a>
    <a href="@Url.Action("ColumnChart")" class="active btn btn-primary">Column Chart</a>
</body>
</html>

Piiii.web/Views/VisualizeData/PieChart.cshtml
@{
    Layout = "~/Views/Shared/Layout1.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeStudentResult", "VisualizeData")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Jour Travailler');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.stdName, obj.marksObtained]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Employes Performance",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="piechart_div"></div>
    <a href="PieChart" class="active btn btn-danger">Pie Chart</a>
    <a href="ColumnChart" class="btn btn-primary">Column Chart</a>
</body>
</html>